### ISSUE TITLE
Project ideas

### ISSUE THREAD

**Issue by paulo-ferraz-oliveira** [spawnfest/spawnfest.github.io#123]
I think it'll work better if we put those here (instead of pull-requesting); we can then sort out some (or even leave all) and update the website. (or even create a wiki page and point there). @pablocostass @starbelly @filipevarjao

**Comment by paulo-ferraz-oliveira** [comment]
#1 read a spreadsheet with emails, names, and other info, and spit out a message that is ready to sent to a potential sponsor at the touch of a button...

**Comment by paulo-ferraz-oliveira** [comment]
#2 a rebar3_vendor (I know one named like this exists already, but it's a coincidence) that takes a bunch of files and changes their names and content to properly vendor them in a consumer.

**Comment by paulo-ferraz-oliveira** [comment]
#3 a rebar3_lfe plugin (use LFE code in your Erlang code) - and all the possible variants for all the possible languages would be other ideas as well

**Comment by paulo-ferraz-oliveira** [comment]
#3 a way to safely store passwords (think transcrypt or git-secret) that is native BEAM: wanna push to a repo but have sensitive info hidden? Use the result of this idea :)

**Comment by paulo-ferraz-oliveira** [comment]
#5 a visual code coverage reporting tool with history

**Comment by starbelly** [comment]
#5 Concurrent release start for OTP applications

**Comment by paulo-ferraz-oliveira** [comment]
#7 a pub-sub lib.

**Comment by starbelly** [comment]
#6 Non-blocking application shutdown in OTP

**Comment by paulo-ferraz-oliveira** [comment]
#9 a way to, given a folder full of random projects (e.g. rebar3 or mix -based) determine what would be the best way to bump dep.s in them: tree analysis + upstream analysis

**Comment by starbelly** [comment]
#10 Markdown lib in erlang

**Comment by paulo-ferraz-oliveira** [comment]
#11 a lib that concentrates good CI practices (testing, analysis, etc.) with an easy way to spawn other lib.s by a template if defines

**Comment by paulo-ferraz-oliveira** [comment]
#12 an Application Performance Monitoring (APM) lib.

**Comment by paulo-ferraz-oliveira** [comment]
#13 a copyright-header-creator lib. (add an easy copyright - or update an existing one - to all your source files)

**Comment by ferd** [comment]
A library to access certificate bundles from the operating system rather than having to carry them with the application. This is a total nightmare on some OSes though.

**Comment by elbrujohalcon** [comment]
I'll throw a bunch of ideas here… I didn't check if there's already something like that out there, but if there are… teams can build these anyway, just for the fun of it or to give it a different BEAM-ish spin.

- A website to organize recurring events (in the style of Meetup but for stuff that happens _every week_). I'm thinking about… say… a group of friends that gather every week in the same place to play soccer, watch movies, read books, or hike.
- A public sports field status tracker app/website. This service would allow players to share the status of public sports facilities (i.e. table tennis tables, basketball rings, soccer fields, etc.) around the city. You will be able to know if they're free or if your friends are there or even what's the weather like there, without actually moving to that location.
- An auto-emoji creator for Slack/Discord, i.e. a slack plugin that when you write :bananas:, if there is no emoji yet for that… it will detect that, try to guess what you mean by that, find out a proper image for it and upload it to that slack workspace so that :bananas: immediately turns into 🍌  without you having to actually create that emoji yourself.

**Comment by lhoguin** [comment]
Gun could use an event handler that traces HTTP requests/responses and even TLS stuff the same way `curl -vvvvvvv` does.

**Comment by hauleth** [comment]
@paulo-ferraz-oliveira

> Application Performance Monitoring (APM) lib

There is [OpenTelemetry](https://github.com/open-telemetry/opentelemetry-erlang)

> a rebar3_lfe plugin (use LFE code in your Erlang code)

https://github.com/lfe-rebar3/rebar3_lfe

@ferd

> A library to access certificate bundles from the operating system rather than having to carry them with the application. This is a total nightmare on some OSes though.

I was thinking about it as well, however it would work only on Windows and macOS machines, as neither Linux nor *BSD have single CA store that could be used. So while on Windows and macOS we can provide functions to check validity of certs, on other OSes it would be guessing until we find matching store.

---

My ideas that I wanted to test out during this SF:

1. Distributed systemd scheduler, that would allow me to have multiple machines and use their systemd instance to schedule and manage the applications there. Just BEAM reimplementation of [fleetctl](https://manpages.debian.org/testing/fleet/fleetctl.1.en.html) from CoreOS
2. ASCIIDoc formatter in Erlang, as I do not really like Markdown/CommonMark as a documentation format. No support for backward-compatible extensions is biggest con.
3. RSS/email/NNTP client that would work similarly to Hey.com, but would allow reading news and mailing groups in tree-like format.
4. Vulnerabilities store that would cooperate with Hex about the issues with the projects there. That should cooperate with CycloneDX SBoM and should provide API for GitHub/GitLab to provide the security notifications.

**Comment by hauleth** [comment]
@lhoguin

> Gun could use an event handler that traces HTTP requests/responses and even TLS stuff the same way `curl -vvvvvvv` does.

I think that such project would suit better for GSoC, because SpawnFest is more about creating new projects. It could be done by adding `telemetry` to Gun.

**Comment by lhoguin** [comment]
> 2. ASCIIDoc formatter in Erlang, as I do not really like Markdown/CommonMark as a documentation format. No support for backward-compatible extensions is biggest con.

https://github.com/ninenines/asciideck

> > Gun could use an event handler that traces HTTP requests/responses and even TLS stuff the same way `curl -vvvvvvv` does.
> 
> I think that such project would suit better for GSoC, because SpawnFest is more about creating new projects. It could be done by adding `telemetry` to Gun.

It doesn't have to be built-in, and I have no plans to add `telemetry` or other to my projects. Gun already has an interface exposing just about everything so `telemetry` users can build on top of that.

**Comment by kanatohodets** [comment]
Riffing off of Paolo's #12: a library to aggregate crashes and stacktraces, so a human operator (or a UI, like observer / LiveDashboard) can view a table of the top X process crashes in time period Y, along with their stacktraces.

Bonus points if it is filterable by application, MFA, or otherwise searchable in some way (e.g., text search against the stacktraces). Perhaps visualizable in a table like this:

Top crashes last 30 minutes:
| Count | Application | Top of the stack | MFA
| --------------- | --------------- | --------------- | ------------- |
| 491 | :hamster_shop_ui | (RuntimeError) OH NO | HamsterShopWeb.PageLive.handle_event/3 
| 30 | :hamster_shop_cron | (UndefinedFunctionError) function :ets.new/1 is undefined or private | HamsterCron.aggregate_purchases_for_report/2
...

I'm not super familiar with SASL, but maybe this idea is somewhat similar to the SASL report browser, or [BigWig's report browsing](https://github.com/beamspirit/bigwig#sasl-report-browsing).

**Comment by wojtekmach** [comment]
> A library to access certificate bundles from the operating system rather than having to carry them with the application. This is a total nightmare on some OSes though.

> I was thinking about it as well, however it would work only on Windows and macOS machines, as neither Linux nor *BSD have single CA store that could be used. 

@ferd @hauleth I was experimenting with it the other day and came up with https://github.com/wojtekmach/system_castore with just the macOS and basic Linux support for now. If you have any feedback or ideas, feel free to submit new issues or comment on https://github.com/wojtekmach/system_castore/issues/1. If such project would be useful for rebar3 in particular, happy to rewrite it in Erlang to make it trivial to vendor in.

**Comment by lhoguin** [comment]
Calendar library with TZ, sub second and anything else `calendar` is currently missing. (Bonus points if it can be integrated directly into `calendar` later on.)

Unicode manipulation library. The `string` module does not provide a number of operations that have to be implemented by hand (such as removing accented characters). (Bonus points if it can be integrated directly into `string` later on.)

Alternatively, support for UTF-16/UTF-32.

cc @galdor

**Comment by adolfont** [comment]
Something like Hedy but for Elixir https://www.hedycode.com/.

Hedy is gradual programming language

OK, maybe that's too much for one spawnfest team, but maybe it would be possible to create a site like  https://www.hedycode.com/hedy?lang=en where ther resulting code looks like Elixir.

**Comment by hauleth** [comment]
@paulo-ferraz-oliveira

> APM's not mentioned on the README

What people mean by "APM" is traces. And that is the main goal of OpenTelemetry and currently only finished part of the specs. Rest of pillars (metrics and logs) is still in the works.

> I read the doc.s and couldn't find an example of how I'd import LFE into Erlang

Just define LFE module and then call it `lfe_module:function()`. Just see the [Hello BEAM](https://github.com/wojtekmach/hello_beam) project by @wojtekmach.

> maybe it would be possible to create a site like https://www.hedycode.com/hedy?lang=en where ther resulting code looks like Elixir.

Website allowing for running Elixir code in browser would be awesome. Languages compiled to machine code have these ([Play Rust](https://play.rust-lang.org) and [GoLang Playground](https://play.golang.org/)) so I do not see why Elixir couldn't have one. Maybe Lumen will help with that.

**Comment by paulo-ferraz-oliveira** [comment]
> What people mean by "APM" is traces.

I know what APM is 😄 I just didn't read the README completely, and stated a fact: it doesn't say APM anywhere. If only time was infinite...

> Just define LFE module and then call it lfe_module:function(). Just see the Hello BEAM project by @wojtekmach.

That's a nice project, and the concept is the same, but it doesn't show how to use `rebar_lfe` to import LFE to Erlang (I don't mean the BEAM generically, but Erlang). (unless it does, and I couldn't find it). 😕 No matter, I'll try this in my own time, when I find it...

**Comment by hauleth** [comment]
@lhoguin

> Alternatively, support for UTF-16/UTF-32.

There is [`unicode:characters_to_binary/3`](https://erlang.org/doc/man/unicode.html#characters_to_binary-3) that supports it. This module also supports normalisation.

> it doesn't show how to use rebar_lfe to import LFE to Erlang 

Well, as long as the compiler ran by Rebar produces `.beam` file the Erlang will not care. Proof of concept - https://github.com/hauleth/example-lfe. You can call it easily both ways, and if you want, you can make it a dependency of your project and it should work without problems as well.

**Comment by paulo-ferraz-oliveira** [comment]
> https://github.com/hauleth/example-lfe

This is the life! Thanks. Will go into "Ref. repo.s". @starbelly, we could even try to find some space in EEF to promote this type of stuff: "We support the ecosystem, ... and here are example on how to use multiple languages in the same project". (e.g. erlef/beam-interop - and then we'd pull from the various existing repo.s with a table of correspondence, 30*29 😄).

**Comment by peerst** [comment]
Currently Leex https://erlang.org/doc/man/leex.html the lexical analyser generator for Erlang does not support column numbers for the generated scanners.  The returned tokens contain only a line number and not a tuple of {line(), column()}

This doesn't matter for the Erlang compiler because it doesn't use a leex generated scanner but all languages that do use leex can't support column numbers in error messages because of that.  For backwards compatibility this should probably be optional.

To make it useful this should aim getting towards a PR against OTP

**Comment by pablocostass** [comment]
Hello there! 👋 

I am reviving this old issue for a SpawnFest unrelated matter. The Erlang Ecosystem Foundation is applying for this year's GSoC and I was wondering if any of the ideas you all proposed would be something you would like to mentor? If that is the case, please do open an issue at https://github.com/erlef/gsoc/issues :)
